services:
  backend:
    build:
      context: ./Backend
    container_name: budgetApp-backend
    restart: always
    networks:
      - main_network
    ports:
      - "5053:5053"
    volumes:
      - /root/main/budgetApp/backend/logs:/app/logs
      - /root/main/budgetApp/backend/.env:/app/.env
      # - /root/main/budgetApp/backend/google:/app/google
      # - /root/main/budgetApp/backend/emaildata.js:/app/emaildata.js
    environment:
      - DB_HOST=main_db
      - BACKEND_ORIGIN=https://budgetapi.msliwowski.net
  app:
    build:
      context: ./Frontend
    container_name: budgetApp-frontend
    restart: always
    networks:
      - main_network
    ports:
      - "127.0.0.1:5052:80"
    environment:
      - FRONTEND_ORIGIN=https://budgetapp.msliwowski.net
    

networks:
  main_network:
    external: true
    name: main_network